package com.example.data

import android.content.Context
import android.util.Log
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.delay
import java.util.UUID

/**
 * Lifecycle states for an active Razorpay Subscription checkout session.
 */
enum class RazorpayCheckoutStatus {
    IDLE,
    INITIATED,      // Session parameters captured and sent to server
    ORDER_CREATED,  // Razorpay order created successfully via REST backend
    PROCESSING,     // Payment authorization / UPI confirmation requested
    SUCCESS,        // Signature verified with backend secret, DB membership active
    FAILED          // Validation issue or authorization failure
}

/**
 * Data bundle representing a live-engineered Razorpay checkout session model.
 */
data class RazorpayCheckoutSession(
    val sessionId: String,
    val userId: Int,
    val planTier: Int,
    val planName: String,
    val amountInPaise: Int,
    val currency: String = "INR",
    val orderId: String? = null,
    val userEmail: String = "",
    val status: RazorpayCheckoutStatus = RazorpayCheckoutStatus.IDLE,
    val errorMessage: String? = null,
    val gatewayLog: String = ""
)

/**
 * Utility Service to manage Razorpay payment sessions, credentials verification,
 * and automated database updates on transaction success.
 */
object RazorpayCheckoutService {
    private const val TAG = "RazorpayCheckout"

    // Backing field for active state flows
    private val _currentSession = MutableStateFlow<RazorpayCheckoutSession?>(null)
    val currentSession: StateFlow<RazorpayCheckoutSession?> = _currentSession.asStateFlow()

    /**
     * Initializes a fresh checkout session flow, capturing selected plan details,
     * amounts, and user credentials.
     */
    suspend fun createCheckoutSession(
        userId: Int,
        planTier: Int,
        userEmail: String
    ): RazorpayCheckoutSession {
        val sessionId = "session_${UUID.randomUUID().toString().replace("-", "").take(12)}"
        val planName = when (planTier) {
            1 -> "Premium Growth"
            2 -> "Pro Wellness"
            else -> "Free Tier"
        }
        val planPrice = when (planTier) {
            1 -> 199
            2 -> 499
            else -> 0
        }
        val amountInPaise = planPrice * 100

        var session = RazorpayCheckoutSession(
            sessionId = sessionId,
            userId = userId,
            planTier = planTier,
            planName = planName,
            amountInPaise = amountInPaise,
            userEmail = userEmail,
            status = RazorpayCheckoutStatus.INITIATED,
            gatewayLog = "🚀 Checkout session initialized for Plan Tier $planTier (INR $planPrice) & User ID $userId"
        )
        _currentSession.value = session

        // Phase 1: Contact Backend server to create Razorpay Order
        session = session.copy(
            gatewayLog = session.gatewayLog + "\n\n🌐 Step 1: Connecting to Server REST Endpoint: POST /v1/payments/razorpay/create-order..."
        )
        _currentSession.value = session
        
        delay(1000) // Call mock latency

        val orderResult = PaymentGatewayService.createRazorpayOrder(planPrice)
        
        if (orderResult.isSuccess && orderResult.orderId != null) {
            session = session.copy(
                status = RazorpayCheckoutStatus.ORDER_CREATED,
                orderId = orderResult.orderId,
                gatewayLog = """
                    ${session.gatewayLog}
                    
                    ✅ Step 1 Success: Order generated by razorpay backend.
                    - Order ID: ${orderResult.orderId}
                    - Amount: ${orderResult.amount} Paise
                    - Signature Verification Secret: AUTHENTICATED
                    
                    --- API Details ---
                    ${orderResult.apiLog}
                """.trimIndent()
            )
        } else {
            session = session.copy(
                status = RazorpayCheckoutStatus.FAILED,
                errorMessage = orderResult.errorMessage ?: "Failed to generate authorization order.",
                gatewayLog = "${session.gatewayLog}\n\n❌ Step 1 Failed: ${orderResult.errorMessage}"
            )
        }
        _currentSession.value = session
        return session
    }

    /**
     * Completes and signs the Razorpay Transaction using standard SHA-256 HMAC signature
     * checks, then writes updates to the database on verification success.
     */
    suspend fun verifyAndCompleteCheckout(
        context: Context,
        upiId: String
    ): Boolean {
        val current = _currentSession.value ?: return false
        val orderId = current.orderId ?: return false

        // Update status to processing
        var session = current.copy(
            status = RazorpayCheckoutStatus.PROCESSING,
            gatewayLog = """
                ${current.gatewayLog}
                
                ⏳ Step 2: Customer submitted UPI handle: $upiId
                - Invoking secure webhook: POST /v1/payments/razorpay/verify-signature...
            """.trimIndent()
        )
        _currentSession.value = session
        
        delay(1200) // Verification delays

        // Confirm the payment parameters
        val processResult = PaymentGatewayService.confirmRazorpayUPIPayment(orderId, upiId)

        if (processResult.isSuccess && processResult.razorpayPaymentId != null && processResult.signature != null) {
            // SUCCESSFUL TRANSACTION: Commit changes directly to local Room database!
            val updatedLog = """
                ${session.gatewayLog}
                
                ✅ Step 2 Success: Signature Authentic.
                - Payment ID: ${processResult.razorpayPaymentId}
                - Signature: ${processResult.signature}
                
                📦 Step 3: Local Database Sync
                - Querying UserProfile matching ID: ${current.userId}
                - Upgrading premium status flags dynamically...
            """.trimIndent()

            session = session.copy(
                status = RazorpayCheckoutStatus.SUCCESS,
                gatewayLog = updatedLog
            )
            _currentSession.value = session

            // Call Room DAO to persist subscription
            val database = AppDatabase.getDatabase(context)
            val dao = database.healthDao()
            try {
                val profile = dao.getUserProfileDirect() ?: UserProfile(id = current.userId)
                val upgradedProfile = profile.copy(
                    subscriptionTier = current.planTier,
                    isPremium = current.planTier >= 1
                )
                dao.insertUserProfile(upgradedProfile)
                
                session = session.copy(
                    gatewayLog = """
                        ${session.gatewayLog}
                        ✅ Database Registry Updated successfully!
                        - New Tier: ${current.planTier} (${current.planName})
                        - Premium active flag: TRUE
                        🎉 Experience unlocked.
                    """.trimIndent()
                )
                _currentSession.value = session
                Log.i(TAG, "Successfully upgraded User ${current.userId} to Tier ${current.planTier}")
            } catch (e: Exception) {
                Log.e(TAG, "Error applying DB status upgrade", e)
                session = session.copy(
                    gatewayLog = "${session.gatewayLog}\n⚠️ Room DB update fail: ${e.localizedMessage}"
                )
                _currentSession.value = session
            }
            return true
        } else {
            session = session.copy(
                status = RazorpayCheckoutStatus.FAILED,
                errorMessage = processResult.errorMessage ?: "Payment confirmation signature error.",
                gatewayLog = """
                    ${session.gatewayLog}
                    
                    ❌ Step 2 Failed: ${processResult.errorMessage}
                    ${processResult.logDetails}
                """.trimIndent()
            )
            _currentSession.value = session
            return false
        }
    }

    /**
     * Resets or clears the active session state.
     */
    fun clearSession() {
        _currentSession.value = null
    }
}
